'use client';

import { ContentNodeMenu } from '@/features/graph/components/ContentNodeMenu';
import type { ContentTemplateId } from '@/features/editor/contentTemplates';
import { useState, useRef, useLayoutEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Handle, Position, type NodeProps } from '@xyflow/react';
import { NodeEditorPanel } from '@/features/editor/NodeEditorPanel';
import { useYjsProvider } from '@/hooks/useYjsProvider';
import { useWorkspaceLayout } from '@/app/workspace/context';
import { showToast } from '@/components/ui/toastStore';
import {
  COLOR_PALETTE,
  MAIN_NODE_COLOR,
  figmaNodeColorOf,
  titleTextOnDeep,
} from '@/features/graph/constants/colors';
import NodeContextMenu from '@/components/ui/NodeContextMenu';
import type {
  CollapseButtonView,
  CollapseSide,
} from '@/features/graph/logic/traversal';

// 같은 userId는 항상 같은 커서 색상을 갖도록 보장 (협업 시 사용자 식별용)
function getUserCursorColor(userId: string): string {
  if (!userId) return COLOR_PALETTE[0].text;
  let hash = 0;
  for (let i = 0; i < userId.length; i++) {
    hash = userId.charCodeAt(i) + ((hash << 5) - hash);
  }
  return COLOR_PALETTE[Math.abs(hash) % COLOR_PALETTE.length].text;
}

// 콘텐츠 노드 뾰족 배너 path — 왼쪽(또는 우측) 둥근 모서리 + 자식 방향 뾰족 점.
// SVG stroke로 그려야 테두리 두께가 어느 변에서도 균일하다(clip-path 스케일링은 점 쪽이 두꺼워짐).
function contentBannerPath(w: number, h: number, pointRight: boolean): string {
  const p = 14; // 점 깊이(크기와 무관하게 고정)
  const r = Math.max(2, Math.min(10, h / 2 - 1)); // 둥근 모서리 반경
  return pointRight
    ? `M ${r},0 H ${w - p} L ${w},${h / 2} L ${w - p},${h} H ${r} Q 0,${h} 0,${h - r} V ${r} Q 0,0 ${r},0 Z`
    : `M ${w - r},0 H ${p} L 0,${h / 2} L ${p},${h} H ${w - r} Q ${w},${h} ${w},${h - r} V ${r} Q ${w},0 ${w - r},0 Z`;
}

export interface NodeViewer {
  clientId: number;
  name: string;
  color: string;
}

export type NodeView = {
  title?: string;
  color?: string;
  textColor?: string; // 텍스트 색상
  isMain?: boolean; // 중심 노드인지 서브 노드인지 구분
  isContentNode?: boolean; // 콘텐츠 노드(부모가 프로젝트가 아님) — GraphCanvas에서 계산해 주입
  autoGenerated?: boolean; // 회의 녹음으로 자동 생성된 노드(S1) — 배지 표시. 회의 기능이 플래그를 넣기 전까진 미표시
  handleSide?: 'left' | 'right';
  hasParent?: boolean; // 부모 노드 존재 여부
  showInputBox?: boolean; // 입력박스 표시 여부
  dockIndex?: number; // 우측 도크 에디터 순번(C3/C4) — 열린 패널 중 위치
  editorBreadcrumb?: string; // 도크 헤더 경로 "프로젝트 > 타이틀"
  panelZIndex?: number; // 패널 z-index (포커스된 패널이 위)
  isHovered?: boolean; // 드래그 중 hover 상태
  workspaceId?: string; // 전체화면 이동 시 query param으로 사용
  viewers?: NodeViewer[]; // 이 노드를 보고 있는 다른 유저들
  isContextMenuOpen?: boolean; // 컨텍스트 메뉴 표시 여부
  isDraft?: boolean;
  isRenaming?: boolean; // 인라인 이름 편집 중(G5·G7 "이름 바꾸기")
  onStartRename?: (nodeId: string) => void; // 인라인 이름 편집 시작
  onFinishRename?: (nodeId: string) => void; // 인라인 이름 편집 종료
  onAddChild?: (nodeId: string, side?: 'left' | 'right', templateId?: ContentTemplateId) => void; // G4·C1 hover "+" 자식 노드 추가
  collapseButtons?: CollapseButtonView[]; // 접기 버튼 표시 정보 (방향별)
  onToggleNodeType?: (nodeId: string) => void; // 프로젝트 ↔ 일반 노드 타입 토글
  onDeleteNode?: (nodeId: string) => void; // 노드 삭제 (확인 모달 경유)
  onClosePanel?: (nodeId: string) => void; // 패널 닫기
  onForwardPanel?: (nodeId: string) => void; // 패널 포커스
  onChange?: (nodeId: string, value: string) => void;
  onToggleCollapse?: (nodeId: string, side: CollapseSide) => void;
};

export function TextUpdaterNode({ data, id, selected }: NodeProps) {
  const router = useRouter();
  const nodeData = data as NodeView;
  const isMain = nodeData.isMain ?? false;
  // 프로젝트 → 타이틀 → 콘텐츠. 타이틀=프로젝트 직계(pill), 콘텐츠=그 이하(연한 사각형) (Figma 08 G1).
  // depth는 서버 미전파로 stale할 수 있어 GraphCanvas가 부모-main 여부로 계산해 넘긴 값을 쓴다.
  const isContent = !isMain && (nodeData.isContentNode ?? false);
  const isTitle = !isMain && !isContent; // 타이틀/단독 노드
  // 저장된 색(rgb(var(--ds-sub-blue)) 등)에서 Figma 08 팔레트 매칭 — 기존 그래프도 자동 적용
  const fig = figmaNodeColorOf(nodeData.color as string | undefined);
  const hasParent = nodeData.hasParent ?? true; // 기본값은 부모가 있다고 가정
  const showInputBox = nodeData.showInputBox ?? false;
  const isContextMenuOpen = nodeData.isContextMenuOpen ?? false;

  const { userMe } = useWorkspaceLayout();
  const userName = userMe?.username ?? 'Anonymous';
  const cursorColor = getUserCursorColor(userMe?.userId ?? '');

  const [isNodeHovered, setIsNodeHovered] = useState(false);
  const [hoverSide, setHoverSide] = useState<'left' | 'right'>('right');
  const [isContentMenuOpen, setIsContentMenuOpen] = useState(false);
  // 콘텐츠 배너 SVG를 노드 실제 px 크기에 맞춰 그리기 위한 측정
  const contentBoxRef = useRef<HTMLDivElement>(null);
  const [contentSize, setContentSize] = useState({ w: 0, h: 0 });
  useLayoutEffect(() => {
    const el = contentBoxRef.current;
    if (!el) return;
    const measure = () =>
      setContentSize({ w: el.offsetWidth, h: el.offsetHeight });
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);
  const collapseButtons = nodeData.collapseButtons ?? [];
  const { provider: collabProvider } = useYjsProvider({
    nodeId: isNodeHovered || showInputBox ? id : null,
    userName,
    userColor: cursorColor,
  });
  const sideRelativeToParent = (nodeData.handleSide ?? 'right') as
    | 'left'
    | 'right';
  const addSide = isMain ? hoverSide : sideRelativeToParent;
  const sourceHandlePosition =
    sideRelativeToParent === 'left' ? Position.Left : Position.Right;
  const viewers = (nodeData.viewers ?? []) as NodeViewer[];
  const isHovered = nodeData.isHovered ?? false;

  // 플레이스홀더는 온보딩·사용법과 동일한 "주제" 어휘로 통일 (#204 용어 정리)
  const PLACEHOLDER = isMain ? '중심 주제' : isTitle ? '타이틀 이름 입력' : '콘텐츠 이름 입력';

  const label = nodeData.title || '';
  const isEmpty = label === '';
  const isRenaming = nodeData.isRenaming ?? false;
  // 채워진 글자색(인라인 input·비어있지 않은 라벨 공용): 타이틀은 Deep 대비색, 그 외는 계열색
  const filledTextColor = isMain ? '#363636' : nodeData.isDraft ? (nodeData.textColor || '#4B4B4B') : isTitle
    ? (titleTextOnDeep(fig?.deep) ??
      nodeData.textColor ??
      'rgb(var(--foreground))')
    : nodeData.textColor || 'rgb(var(--foreground))';
  /*
   * CONTEXT
   * - Problem      : one gray placeholder color loses contrast on the dark blue title-node background.
   * - Why          : reuse titleTextOnDeep so placeholder contrast follows the same palette decision as filled text.
   * - Alternatives : a fixed light gray would be hard to read on pale nodes; checking every CSS color needs DOM measurement.
   * - Trade-offs   : dark title nodes get a translucent white placeholder, while other nodes keep the existing gray.
   * - Edge Case    : the shared color check also covers legacy nodes mapped to the blue Figma palette.
   */
  const hasDarkTitleBackground = isTitle && titleTextOnDeep(fig?.deep) !== null;
  const placeholderColor = hasDarkTitleBackground
    ? 'rgba(255, 255, 255, 0.72)'
    : 'rgb(var(--ds-gray-500))';

  // 중심 노드: 네모난 형태, 큰 패딩, 배경 없이 테두리만
  // 서브 노드: 동그란 형태, 작은 패딩, 배경색 채움
  /*
   * CONTEXT
   * - Problem      : 프로젝트 박스의 좌상단 곡선이 폴더 탭과 겹쳐 선택 시 틈처럼 보인다.
   * - Why          : 박스와 hover 레이어의 좌상단 반경을 1px로 줄여 탭과 자연스럽게 이어 붙인다.
   * - Alternatives : 탭 위치 조정은 기존 폴더 실루엣까지 바꾸므로 제외한다.
   * - Trade-offs   : 프로젝트 박스의 좌상단만 작은 곡률을 쓰고 나머지 모서리는 유지된다.
   * - Edge Case    : 선택·hover 모두 같은 모양을 쓰며 타이틀·콘텐츠 노드는 유지한다.
   */
  const containerClasses = isMain
    ? 'text-updater-node rounded-[14px] rounded-tl-[1px]'
    : isContent
      ? 'text-updater-node' // 모양은 아래 clip-path 배경 레이어가 그린다(오른쪽 뾰족 배너)
      : 'text-updater-node rounded-full';

  // React Flow 기본 엣지 색상과 동일한 회색 (#b1b1b7)
  const EDGE_COLOR = '#D9D9D9';

  /*
   * CONTEXT
   * - Problem      : Figma 08(C3 등)은 엣지가 노드에 닿는 지점마다 흰 채움+회색 링의 원형
   *                  포트 점을 "항상" 표시하는데, 현재 핸들은 hover 시에만(opacity 토글)
   *                  보이고 기본 React Flow 다크닷 스타일이라 시안과 다르다.
   * - Why          : 핸들은 이미 연결 접점이므로, 실제 엣지가 있는 접점(부모 쪽 target /
   *                  자식 있는 쪽 source)만 상시 점으로 노출한다. 자식·부모 유무는 기존
   *                  collapseButtons(방향별 자식 유무)·hasParent로 판정 — 엣지 배열 조회
   *                  없이 노드 data만으로 결정되어 드래그 중에도 일관.
   * - Alternatives : 모든 핸들 상시 노출 — 자식 없는 변에도 점이 떠 시안과 다름, 기각.
   *                  엣지 배열을 노드에 주입해 접점 집계 — data 계약 확장·리렌더 비용, 기각.
   * - Trade-offs   : 자식 없는 변의 source 핸들은 여전히 hover 시에만(새 연결 드래그용)
   *                  노출 → 상시 점과 hover 점이 공존하지만 둘 다 동일 PORT_DOT_STYLE이라
   *                  시각 일관. 포트 치수·색은 C3 육안 근사치(실측 후 조정 예정).
   * - Edge Case    : root(부모 없음)의 target 핸들은 엣지가 없으므로 계속 숨김(opacity 0).
   */
  const childSides = new Set(collapseButtons.map((b) => b.side));
  // Figma 08 실측: 포트 점 지름 14px, 흰 fill + 2px #727272 링(엣지선과 동일 색)
  /*
   * CONTEXT
   * - Problem      : 타이틀·콘텐츠·핸들의 그림자가 흐리거나 없어 참고 이미지의 깊이감이 부족하다.
   * - Why          : 본체는 아래 3px, 작은 핸들은 아래 2px 그림자로 크기에 맞춰 강조한다.
   * - Alternatives : 전체 노드 필터는 자식 버튼과 핸들까지 중복으로 그림자를 적용한다.
   * - Trade-offs   : 콘텐츠 SVG는 외곽을 따르는 필터 렌더링 비용이 유지된다.
   * - Edge Case    : 선택 링과 핸들의 숨김·연결 영역은 기존 동작을 유지한다.
   */
  const PORT_DOT_STYLE = {
    width: 14,
    height: 14,
    minWidth: 14,
    minHeight: 14,
    boxShadow: '0 2px 2px rgba(53, 62, 112, 0.28)',
    background: '#ffffff',
    border: `2px ${nodeData.isDraft ? 'dashed' : 'solid'} #727272`,
    borderRadius: '50%',
  } as const;

  const viewerBorderColor = viewers.length > 0 ? viewers[0].color : null;

  // 콘텐츠 노드 = 자식(엣지가 나가는) 방향으로 뾰족한 배너. 모양은 SVG path로 그리고
  // 컨테이너는 투명 유지 → 핸들(컨테이너 직속)이 안 잘린다(React Flow #008 회피).
  const pointRight = sideRelativeToParent === 'right';
  const baseContentFill = fig?.light ?? nodeData.color ?? 'rgb(var(--ds-sub-gray))';
  const contentFill = nodeData.isDraft ? `color-mix(in srgb, ${baseContentFill} 55%, white)` : baseContentFill;
  /*
   * CONTEXT
   * - Problem      : 텍스트 노드의 선택 테두리가 요청한 색과 다르고 hover 색에 덮인다.
   * - Why          : 선택을 우선 판정해 지정 색 #3F62E0를 그대로 사용한다.
   * - Alternatives : 전역 선택 토큰 변경은 다른 노드의 선택 색까지 바꾼다.
   * - Trade-offs   : 콘텐츠 선택 색을 이 컴포넌트에서 명시적으로 관리한다.
   * - Edge Case    : 선택 중 hover에도 색을 유지하고 미선택 협업 테두리는 유지한다.
   */
  const contentRing = selected
    ? '#3F62E0'
    : isHovered
      ? '#93C5FD'
      : (viewerBorderColor ?? '#ffffff');

  // main 노드 기본 테두리는 자기 그래프 색 — 흰 배경 유지 규칙 안에서 소속 그래프를 드러낸다.
  // 파스텔 톤(--ds-sub-*)은 1px로는 식별이 어려워 색이 있으면 2px로 표시.
  // 색 미저장 legacy main은 회색(EDGE_COLOR) 폴백.
  const mainOwnBorderColor = nodeData.color || null;
  /*
   * CONTEXT
   * - Problem      : selection was drawn on the card alone, leaving the folder tab outside the selected silhouette.
   * - Why          : use one pale-blue outer ring for the card and extend the same layered folder shape over its upper-left tab.
   * - Alternatives : a rectangular outline clips the folder profile; a tinted card changes its white surface.
   * - Trade-offs   : the selection ring adds visual space around the main node without changing its content dimensions.
   * - Edge Case    : title nodes keep their pill shape and receive a matching ring around their small upper-left cap.
   */
  const selectionRing = '#B7C7FF';
  /*
   * CONTEXT
   * - Problem      : hover 테두리와 탭 배경이 본체의 선택 실루엣·절반 강조와 분리된다.
   * - Why          : hover와 선택의 외곽을 공유하고 왼쪽 강조색을 탭 내부까지 연결한다.
   * - Alternatives : 별도 hover 테두리는 두께와 탭 접합부가 어긋난다.
   * - Trade-offs   : hover에서도 선택과 같은 외곽이 보이며 절반 배경으로 방향을 구분한다.
   * - Edge Case    : 오른쪽 hover는 탭 내부의 흰색을 유지하고 선택 중에도 방향을 강조한다.
   */
  const mainHighlighted = selected || isNodeHovered || isHovered;
  const mainHoverFill = '#EAEDFF';
  const mainFolderRing = mainHighlighted
    ? selectionRing
    : (viewerBorderColor ?? '#ffffff');

  const containerStyle = isMain
    ? {
        // 프로젝트(main) 노드는 그래프 색을 데이터로 보유해도 항상 흰 배경 (도메인 규칙).
        // Figma 08(G1): 흰 카드 + 소프트 섀도 + 좌상단 폴더 탭(탭 색 = 그래프 색)으로
        // 소속 그래프를 드러낸다 → 기존 '색 테두리'를 폴더 탭(mainOwnBorderColor)으로 대체,
        // 기본 테두리 없음. hover/selected/viewer만 테두리로 표시.
        backgroundColor: MAIN_NODE_COLOR.bg,
        boxShadow: mainHighlighted
          ? `0 0 0 8px ${selectionRing}, 0 3px 4px rgba(53, 62, 112, 0.24)`
          : '0 3px 4px rgba(53, 62, 112, 0.24)',
        border: mainHighlighted
          ? 'none'
          : viewerBorderColor
            ? `2px solid ${viewerBorderColor}`
            : 'none',
      }
    : isContent
      ? {
          // 콘텐츠 노드: 모양(뾰족 배너 + 흰 테두리 + 섀도)은 아래 clip-path 레이어가 그린다.
          // 컨테이너는 투명·사각형 유지해야 핸들이 안 잘린다.
          backgroundColor: 'transparent',
          border: 'none',
        }
      : {
          // 타이틀 노드(main 직계 자손): Node Deep fill + 흰 테두리 4px + 소프트 섀도 + 흰 꽁다리(아래).
          // 글자는 어두운 Deep(파랑)만 흰색, 밝은 Deep은 계열 어두운색. (Figma 08 실측)
          backgroundColor:
            (nodeData.isDraft ? fig?.light : fig?.deep) ??
            `color-mix(in srgb, ${nodeData.color || 'rgb(var(--ds-sub-gray))'} 45%, ${nodeData.textColor || 'rgb(var(--ds-text-gray))'} 55%)`,
          boxShadow: selected
            ? `0 0 0 8px ${selectionRing}, 0 3px 4px rgba(53, 62, 112, 0.28)`
            : '0 3px 4px rgba(53, 62, 112, 0.28)',
          border: isHovered
            ? '4px solid #93C5FD'
            : selected
              ? '4px solid #ffffff'
              : viewerBorderColor
                ? `4px solid ${viewerBorderColor}`
                : '4px solid #ffffff',
        };

  // 최대 3명 표시, 이후 +N
  const visibleViewers = viewers.slice(0, 3);
  const overflowCount = viewers.length - visibleViewers.length;

  return (
    <div className="relative">
      {/* 다른 유저 뷰어 표시 — 노드 위에 배치 */}
      {viewers.length > 0 && (
        <div
          className="absolute flex items-center gap-0.5"
          style={{
            bottom: '100%',
            left: '50%',
            transform: 'translateX(-50%)',
            marginBottom: 4,
            zIndex: 20,
            pointerEvents: 'none',
          }}
        >
          {visibleViewers.map((v) => (
            <div
              key={v.clientId}
              title={v.name}
              className="flex items-center justify-center rounded-full text-white text-[10px] font-bold leading-none select-none"
              style={{
                width: 20,
                height: 20,
                backgroundColor: v.color,
                border: '2px solid white',
                marginLeft: visibleViewers.indexOf(v) > 0 ? -4 : 0,
              }}
            >
              {v.name.charAt(0).toUpperCase()}
            </div>
          ))}
          {overflowCount > 0 && (
            <div
              className="flex items-center justify-center rounded-full bg-gray-400 text-white text-[9px] font-bold leading-none select-none"
              style={{
                width: 20,
                height: 20,
                border: '2px solid white',
                marginLeft: -4,
              }}
            >
              +{overflowCount}
            </div>
          )}
        </div>
      )}

      {/* 컨텍스트 메뉴 - 노드 아래 배치. 루트 기준 왼쪽 노드는 오른쪽 테두리 정렬(왼쪽으로 펼침), 오른쪽 노드는 왼쪽 테두리 정렬(오른쪽으로 펼침) */}
      {isContextMenuOpen && (
        <div
          className="absolute"
          style={{
            top: '100%',
            marginTop: 8,
            zIndex: 50,
            ...(sideRelativeToParent === 'left' ? { right: 0 } : { left: 0 }),
          }}
        >
          <NodeContextMenu
            isProjectNode={isMain}
            onToggleNodeType={() => nodeData.onToggleNodeType?.(id)}
            onRename={() => nodeData.onStartRename?.(id)}
            onDeleteNode={() => nodeData.onDeleteNode?.(id)}
          />
        </div>
      )}

      {/* 노션 에디터 패널 - 노드 뒤에 배치 */}
      {showInputBox && (
        <NodeEditorPanel
          nodeId={id}
          handleSide={sideRelativeToParent}
          workspaceId={nodeData.workspaceId}
          dockIndex={nodeData.dockIndex}
          title={label}
          breadcrumb={nodeData.editorBreadcrumb}
          panelZIndex={nodeData.panelZIndex}
          onExpandClick={() =>
            router.push(
              `/workspace/node/${id}?workspaceId=${nodeData.workspaceId ?? ''}`,
            )
          }
          onClose={() => nodeData.onClosePanel?.(id)}
          onFocus={() => nodeData.onForwardPanel?.(id)}
          collabProvider={collabProvider}
          username={userName}
          cursorColor={cursorColor}
          onFirstLineChange={(text) => nodeData.onChange?.(id, text)}
        />
      )}

      {/*
        CONTEXT
        - Problem      : main·타이틀 노드의 제목을 바로 편집하려면 컨텍스트 메뉴를 거쳐야 한다.
        - Why          : 노드 본체의 더블 클릭을 기존 인라인 이름 편집에 연결해 저장 동작을 재사용한다.
        - Alternatives : 별도 편집 상태와 저장 API를 추가하면 기존 이름 바꾸기와 동작이 중복된다.
        - Trade-offs   : main·타이틀은 제목 편집에 집중하고 본문 에디터는 콘텐츠 노드에서만 연다.
        - Edge Case    : 콘텐츠 노드·버튼·연결 핸들·편집 중 입력창은 더블 클릭으로 편집을 시작하지 않는다.
      */}
      {/* 노드 - 입력박스보다 앞에 배치 */}
      <div
        ref={contentBoxRef}
        className={containerClasses}
        style={{
          ...containerStyle,
          position: 'relative',
          zIndex: 40,
          // 타이틀(main 직계 자손)은 사진처럼 넓은 pill — 짧은 제목도 넓게, 더 길면 확장(최대 300)
          maxWidth: isTitle ? '300px' : '200px',
          minWidth: isMain ? '200px' : isTitle ? '200px' : `${PLACEHOLDER.length}em`,
          minHeight: isMain ? 140 : undefined,
          // 콘텐츠는 뾰족한 쪽에 여유 패딩(글자가 점에 안 겹치게)
          padding: isMain
            ? '48px 24px'
            : isContent
              ? pointRight
                ? '6px 24px 6px 14px'
                : '6px 14px 6px 24px'
              : '6px 12px',
        }}
        onMouseEnter={() => setIsNodeHovered(true)}
        onMouseMove={(event) => {
          if (!isMain) return;
          const rect = event.currentTarget.getBoundingClientRect();
          setHoverSide(event.clientX < rect.left + rect.width / 2 ? 'left' : 'right');
        }}
        onMouseLeave={() => setIsNodeHovered(false)}
        onDoubleClick={(event) => {
          if (isContent || isRenaming) return;
          if ((event.target as HTMLElement).closest('button, .react-flow__handle')) return;
          event.stopPropagation();
          nodeData.onStartRename?.(id);
        }}
      >
        {/*
          CONTEXT
          - Problem      : 프로젝트의 양쪽 추가 방향을 하나의 hover 버튼으로 구분할 수 없다.
          - Why          : 포인터가 위치한 절반을 강조하고 해당 방향으로 생성 요청을 전달한다.
          - Alternatives : 양쪽 버튼 상시 노출은 시안보다 캔버스 조작 요소가 많아진다.
          - Trade-offs   : 절반 강조는 프로젝트에만 적용하며 기존 타이틀 생성은 유지한다.
          - Edge Case    : 버튼으로 이동해도 마지막 hover 방향을 유지한다.
        */}
        {isMain && isNodeHovered && (
          <div aria-hidden className="absolute inset-0 pointer-events-none rounded-[14px] rounded-tl-[1px]" style={{
            overflow: 'hidden', zIndex: -1,
          }}>
            <div style={{ position: 'absolute', top: 0, bottom: 0,
              [hoverSide]: 0, width: '50%', backgroundColor: mainHoverFill }} />
          </div>
        )}
        {/* 콘텐츠 노드 뾰족 배너 — SVG path를 연한 fill + 흰색 uniform stroke로 그린다.
            stroke는 어느 변에서도 두께가 균일(점 쪽도). 핸들은 컨테이너 직속이라 안 잘린다. */}
        {isContent && contentSize.w > 0 && (
          <svg
            aria-hidden
            width={contentSize.w}
            height={contentSize.h}
            className="absolute inset-0"
            style={{
              zIndex: -1,
              overflow: 'visible',
              filter: 'drop-shadow(0 3px 2px rgba(53, 62, 112, 0.28))',
            }}
          >
            <path
              d={contentBannerPath(contentSize.w, contentSize.h, pointRight)}
              fill={contentFill}
              stroke={contentRing}
              strokeWidth={3}
              strokeLinejoin="round"
            />
          </svg>
        )}
        {/*
          CONTEXT
          - Problem      : 프로젝트 탭이 단색 돌출부라 참고 이미지의 흰 폴더 외곽이 없다.
          - Why          : 흰 외곽과 색상 탭을 겹쳐 기존 카드와 하나의 폴더로 보이게 한다.
          - Alternatives : 이미지 배경은 제목 길이와 그래프 색상 변화에 대응하기 어렵다.
          - Trade-offs   : 카드 밖 탭은 시각 장식이며 연결 핸들은 카드 중심을 유지한다.
          - Edge Case    : 선택·협업 강조는 탭에도 반영하고 긴 제목은 기존 두 줄 제한을 유지한다.
        */}
        {isMain && (
          <div
            aria-hidden
            className="absolute pointer-events-none"
            style={{
              top: mainHighlighted ? -22 : -12,
              left: mainHighlighted ? -8 : 0,
              width: mainHighlighted ? 90 : 74,
              height: mainHighlighted ? 22 : 28,
              /*
               * CONTEXT
               * - Problem      : the white folder-tab shell creates a detached clip-like cap on hover.
               * - Why          : using the node ring color for the shell makes the tab join the card outline.
               * - Alternatives : removing the shell loses the folder shape; keeping white preserves the visible gap.
               * - Trade-offs   : the tab shell follows hover, selection, and collaborator outline colors.
               * - Edge Case    : unhighlighted main nodes use a soft blue shell matching the card outline.
               */
              backgroundColor: mainFolderRing,
              borderRadius: mainHighlighted ? '26px 26px 0 0' : '18px 18px 0 0',
              zIndex: 0,
            }}
          >
            {mainHighlighted && <div style={{
              position: 'absolute', top: 8, left: 8, width: 74, height: 14,
              borderRadius: '20px 20px 0 0',
              backgroundColor: isNodeHovered && hoverSide === 'left' ? mainHoverFill : MAIN_NODE_COLOR.bg,
            }} />}
            <div style={{
              position: 'absolute',
              top: mainHighlighted ? 13 : 5,
              left: mainHighlighted ? 15 : 7,
              width: 59,
              height: 15,
              borderRadius: mainHighlighted ? '12px 12px 0 0' : '10px 10px 0 0',
              backgroundColor: fig?.deep ?? mainOwnBorderColor ?? EDGE_COLOR,
            }} />
          </div>
        )}
        {/*
         * CONTEXT
         * - Problem      : 탭의 흰 면과 선택 stroke가 함께 본체에 겹쳐 양옆 색 테두리가 안쪽으로 돌출된다.
         * - Why          : 탭을 52×10px로 넓고 낮게 조정하고 흰 fill만 본체에 2px 겹쳐 접합선을 덮는다.
         * - Alternatives : 선택 링 전체를 제거하면 선택 상태를 구분하기 어려워 접합부만 수정한다.
         * - Trade-offs   : 흰 면과 외곽선을 따로 그려 선택 링이 본체의 흰 테두리를 침범하지 않게 한다.
         * - Edge Case    : 좌우 탭·선택 해제·캔버스 축소에서도 접합부가 벌어지지 않도록 겹침을 유지한다.
         */}
        {isTitle && (
          <svg
            aria-hidden
            className="absolute pointer-events-none"
            width="68"
            height="20"
            viewBox="-8 -8 68 20"
            /*
             * CONTEXT
             * - Problem      : 상단 탭이 프로젝트에서 먼 쪽에 있어 요청한 부모 방향 배치와 반대다.
             * - Why          : 오른쪽 타이틀은 왼쪽 상단, 왼쪽 타이틀은 오른쪽 상단에 탭을 둔다.
             * - Alternatives : 화면 좌표 비교는 드래그 중 연결 방향과 다르게 바뀔 수 있다.
             * - Trade-offs   : 탭 위치는 순간 좌표 대신 그래프의 좌우 배치 방향을 따른다.
             * - Edge Case    : 좌우 대칭 이동 시 handleSide 변경에 맞춰 탭도 함께 이동한다.
             */
            style={{
              top: -22,
              ...(sideRelativeToParent === 'left' ? { right: 10 } : { left: 10 }),
              overflow: 'hidden',
            }}
          >
            {selected && (
              <svg x="-8" y="-8" width="68" height="18" viewBox="-8 -8 68 18" overflow="hidden">
                <path
                  d="M 0 12 V 10 C 4 10 3 0 14 0 H 38 C 49 0 48 10 52 10 V 12"
                  fill="none"
                  stroke={selectionRing}
                  strokeWidth={16}
                  strokeLinejoin="round"
                />
              </svg>
            )}
            <path
              d="M 0 12 V 10 C 4 10 3 0 14 0 H 38 C 49 0 48 10 52 10 V 12"
              fill="#ffffff"
            />
          </svg>
        )}
        {isRenaming ? (
          // 인라인 이름 편집(G5·G7) — input onChange가 handleTitleChange로 즉시+디바운스 저장,
          // Enter/blur로 종료, Esc로 종료(저장은 이미 반영됨). nodrag·stopPropagation로 드래그/에디터 오픈 차단.
          <input
            autoFocus
            defaultValue={label}
            placeholder={PLACEHOLDER}
            onFocus={(e) => e.currentTarget.select()}
            onChange={(e) => nodeData.onChange?.(id, e.currentTarget.value)}
            onBlur={() => nodeData.onFinishRename?.(id)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') e.currentTarget.blur();
              else if (e.key === 'Escape') nodeData.onFinishRename?.(id);
            }}
            onClick={(e) => e.stopPropagation()}
            onDoubleClick={(e) => e.stopPropagation()}
            className={`nodrag w-full bg-transparent outline-none ${
              isContent ? 'text-left' : 'text-center'
            } ${
              hasDarkTitleBackground
                ? 'placeholder:text-[rgba(255,255,255,0.72)]'
                : 'placeholder:text-gray-500'
            }`}
            style={{
              color: filledTextColor,
              fontWeight: isMain ? 700 : isTitle ? 600 : undefined,
              fontSize: isMain ? '30px' : undefined,
              lineHeight: isMain ? '1.4em' : '100%',
              ...(isMain ? {} : { fontFamily: 'Pretendard, sans-serif', fontSize: isTitle ? 13 : 11, fontWeight: isTitle ? 600 : 700, letterSpacing: 0 }),
            }}
          />
        ) : (
          <div
            className={`${isContent ? 'text-left' : 'text-center'} select-none`}
            style={{
              // 타이틀: 어두운 Deep(파랑)만 흰 글자, 밝은 Deep은 계열 어두운색.
              // 콘텐츠/프로젝트: 계열 어두운색(--ds-text-*). (Figma 08 실측)
              color: isEmpty ? placeholderColor : filledTextColor,
              fontWeight: isMain ? 700 : isTitle ? 600 : undefined,
              fontSize: isMain ? '30px' : undefined,
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
              wordBreak: 'break-word',
              lineHeight: isMain ? '1.4em' : '100%',
              ...(isMain ? {} : { fontFamily: 'Pretendard, sans-serif', fontSize: isTitle ? 13 : 11, fontWeight: isTitle ? 600 : 700, letterSpacing: 0 }),
              maxHeight: isMain ? '2.8em' : '2em',
            }}
          >
            {isEmpty ? PLACEHOLDER : label}
          </div>
        )}
        {/*
         * CONTEXT
         * - Problem      : 자식 추가 버튼에 참고 이미지의 흰 테두리와 입체감이 없다.
         * - Why          : 원형 버튼과 라벨에 같은 파란 바탕·흰 외곽·하단 그림자를 적용한다.
         * - Alternatives : 이미지 버튼은 확대와 텍스트 접근성에 불리하다.
         * - Trade-offs   : 테두리를 포함한 버튼 크기가 조금 커진다.
         * - Edge Case    : 좌우 배치와 기존 추가·메뉴 동작은 그대로 유지한다.
         */}
        {/* G4·C1: hover "+" 자식 추가 버튼 — source(자식) 방향. 프로젝트→타이틀, 타이틀→콘텐츠. */}
        {(isMain || isTitle) && (isNodeHovered || isContentMenuOpen) && !isRenaming && (
          <div
            className="nodrag absolute top-1/2 -translate-y-1/2 flex items-center gap-1.5"
            style={{
              ...(addSide === 'left'
                ? {
                    right: '100%',
                    paddingRight: 10,
                    flexDirection: 'row-reverse',
                  }
                : { left: '100%', paddingLeft: 10 }),
              zIndex: 10,
            }}
          >
            <button
              type="button"
              aria-label={isTitle ? '콘텐츠 노드 메뉴 열기' : '타이틀 노드 추가'}
              aria-expanded={isTitle ? isContentMenuOpen : undefined}
              onClick={(event) => {
                event.stopPropagation();
                if (isTitle) setIsContentMenuOpen((open) => !open);
                else nodeData.onAddChild?.(id, addSide);
              }}
              className="flex items-center justify-center rounded-full border-2 border-white text-white shadow-[0_2px_3px_rgba(53,62,112,0.24)] transition-opacity hover:opacity-90"
              style={{ width: 26, height: 26, backgroundColor: '#627AFF' }}
            >
              {/* SVG 십자로 배경원 정중앙 정렬 (텍스트 "+"의 베이스라인 쏠림 제거) */}
              <svg width="11" height="11" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                <path
                  d="M6 1.5V10.5M1.5 6H10.5"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                />
              </svg>
            </button>
            <button
              type="button"
              aria-expanded={isTitle ? isContentMenuOpen : undefined}
              onClick={(event) => {
                event.stopPropagation();
                if (isTitle) setIsContentMenuOpen((open) => !open);
                else nodeData.onAddChild?.(id, addSide);
              }}
              className="whitespace-nowrap rounded-full border-2 border-white text-white select-none shadow-[0_2px_3px_rgba(53,62,112,0.24)]"
              style={{
                backgroundColor: '#627AFF',
                fontSize: 10,
                padding: '4px 10px',
              }}
            >
              {isMain ? '새 타이틀 노드 추가' : '콘텐츠 노드 추가'}
            </button>
            {isTitle && isContentMenuOpen && (
              <div className="absolute top-full z-20 mt-2" style={addSide === 'left' ? { right: 10 } : { left: 10 }}>
                <ContentNodeMenu
                  onClose={() => setIsContentMenuOpen(false)}
                  onSelect={(templateId) => {
                    setIsContentMenuOpen(false);
                    nodeData.onAddChild?.(id, addSide, templateId);
                  }}
                />
              </div>
            )}
          </div>
        )}
        {/* G1-H: 회의 녹음 버튼 (타이틀 노드 위) — 회의 기능 준비 중 시각 스텁.
            녹음 자체(M1~M4)는 별도 담당이라, 지금은 안내 토스트만 띄운다. */}
        {isTitle && isNodeHovered && !isRenaming && (
          <button
            type="button"
            aria-label="회의 녹음"
            onClick={(event) => {
              event.stopPropagation();
              showToast('회의 녹음 기능은 준비 중이에요');
            }}
            className="nodrag absolute bottom-full left-1/2 z-10 mb-2 flex -translate-x-1/2 items-center gap-1.5 whitespace-nowrap rounded-full border border-red-200 bg-background px-3 py-1.5 text-[12px] font-semibold text-red-500 shadow-sm transition-colors hover:bg-red-50"
          >
            <span className="h-2 w-2 rounded-full bg-red-500" aria-hidden="true" />
            회의 녹음
          </button>
        )}
        {/* S1: 회의 녹음으로 자동 생성된 노드 배지 — 회의 기능이 autoGenerated 플래그를
            넣으면 표시된다(지금은 그 데이터가 없어 미노출). */}
        {nodeData.autoGenerated && (
          <span
            className="nodrag absolute -top-2.5 -right-2 z-10 flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold text-white shadow-sm"
            style={{ backgroundColor: 'rgb(var(--ds-main-blue))' }}
          >
            <svg width="9" height="9" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M12 2l1.8 5.2L19 9l-5.2 1.8L12 16l-1.8-5.2L5 9l5.2-1.8z" />
            </svg>
            AI 생성
          </span>
        )}
        {!hasParent ? (
          <>
            <Handle
              type="source"
              position={Position.Left}
              id="source-left"
              style={{
                ...PORT_DOT_STYLE,
                opacity: childSides.has('left') || isNodeHovered ? 1 : 0,
              }}
            />
            <Handle
              type="target"
              position={Position.Left}
              id="target-left"
              isConnectableStart={false}
              style={{ opacity: 0 }}
            />
            <Handle
              type="source"
              position={Position.Right}
              id="source-right"
              style={{
                ...PORT_DOT_STYLE,
                opacity: childSides.has('right') || isNodeHovered ? 1 : 0,
              }}
            />
            <Handle
              type="target"
              position={Position.Right}
              id="target-right"
              isConnectableStart={false}
              style={{ opacity: 0 }}
            />
          </>
        ) : (
          <>
            <Handle
              type="target"
              position={
                sideRelativeToParent === 'right'
                  ? Position.Left
                  : Position.Right
              }
              id={
                sideRelativeToParent === 'right'
                  ? 'target-left'
                  : 'target-right'
              }
              isConnectableStart={false}
              style={{ ...PORT_DOT_STYLE, opacity: 1 }}
            />
            <Handle
              type="source"
              position={sourceHandlePosition}
              id={`source-${sideRelativeToParent}`}
              style={{
                ...PORT_DOT_STYLE,
                opacity:
                  childSides.has(sideRelativeToParent) || isNodeHovered ? 1 : 0,
              }}
            />
          </>
        )}
      </div>
    </div>
  );
}
